PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?termURI ?prefLabel ?scopeNote

WHERE {

?termURI skos:broader <https://data.ihlia.nl/homosaurus/homoit0000878> ;
skos:prefLabel ?prefLabel ;
skos:scopeNote ?scopeNote .

FILTER (lang(?prefLabel) = "nl")
FILTER (lang(?scopeNote) = "nl")

}